"""Add onboarding tables

Revision ID: 79c196e248db
Revises: 44e91a5715fa
Create Date: 2026-06-14 13:09:12.890783

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '79c196e248db'
down_revision: Union[str, Sequence[str], None] = '44e91a5715fa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('onboarding_modules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('assessment_url', sa.Text(), nullable=True),
    sa.Column('order', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_onboarding_modules_id'), 'onboarding_modules', ['id'], unique=False)
    op.create_table('onboarding_team_members',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('role', sa.Text(), nullable=False),
    sa.Column('department', sa.Text(), nullable=False),
    sa.Column('email', sa.Text(), nullable=True),
    sa.Column('linkedin', sa.Text(), nullable=True),
    sa.Column('slack', sa.Text(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_onboarding_team_members_id'), 'onboarding_team_members', ['id'], unique=False)
    op.create_table('onboarding_sections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('module_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('video_url', sa.Text(), nullable=True),
    sa.Column('video_duration', sa.String(length=50), nullable=True),
    sa.Column('quiz_passing_score', sa.Integer(), nullable=True),
    sa.Column('order', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['module_id'], ['onboarding_modules.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_onboarding_sections_id'), 'onboarding_sections', ['id'], unique=False)
    op.create_table('onboarding_documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('section_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['section_id'], ['onboarding_sections.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_onboarding_documents_id'), 'onboarding_documents', ['id'], unique=False)
    op.create_table('onboarding_progress',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('module_id', sa.Integer(), nullable=False),
    sa.Column('section_id', sa.Integer(), nullable=False),
    sa.Column('completed_at', sa.TIMESTAMP(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['module_id'], ['onboarding_modules.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['section_id'], ['onboarding_sections.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_onboarding_progress_id'), 'onboarding_progress', ['id'], unique=False)
    op.create_table('onboarding_quiz_questions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('section_id', sa.Integer(), nullable=False),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('options', sa.JSON(), nullable=False),
    sa.Column('correct_option_index', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['section_id'], ['onboarding_sections.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_onboarding_quiz_questions_id'), 'onboarding_quiz_questions', ['id'], unique=False)
    op.create_table('onboarding_quiz_attempts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('section_id', sa.Integer(), nullable=False),
    sa.Column('chosen_index', sa.Integer(), nullable=False),
    sa.Column('is_correct', sa.Boolean(), nullable=False),
    sa.Column('attempted_at', sa.TIMESTAMP(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['question_id'], ['onboarding_quiz_questions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['section_id'], ['onboarding_sections.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_onboarding_quiz_attempts_id'), 'onboarding_quiz_attempts', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_onboarding_quiz_attempts_id'), table_name='onboarding_quiz_attempts')
    op.drop_table('onboarding_quiz_attempts')
    op.drop_index(op.f('ix_onboarding_quiz_questions_id'), table_name='onboarding_quiz_questions')
    op.drop_table('onboarding_quiz_questions')
    op.drop_index(op.f('ix_onboarding_progress_id'), table_name='onboarding_progress')
    op.drop_table('onboarding_progress')
    op.drop_index(op.f('ix_onboarding_documents_id'), table_name='onboarding_documents')
    op.drop_table('onboarding_documents')
    op.drop_index(op.f('ix_onboarding_sections_id'), table_name='onboarding_sections')
    op.drop_table('onboarding_sections')
    op.drop_index(op.f('ix_onboarding_team_members_id'), table_name='onboarding_team_members')
    op.drop_table('onboarding_team_members')
    op.drop_index(op.f('ix_onboarding_modules_id'), table_name='onboarding_modules')
    op.drop_table('onboarding_modules')
    # ### end Alembic commands ###
