"""add encord_sync_logs table

Revision ID: b539269dd6af
Revises: dac6e132f4d1
Create Date: 2026-08-28 16:47:15.424929

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b539269dd6af'
down_revision: Union[str, Sequence[str], None] = 'dac6e132f4d1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_onboarding_team_members_id'), table_name='onboarding_team_members')
    op.drop_table('onboarding_team_members')

    op.drop_index(op.f('ix_product_managers_id'), table_name='product_managers')
    op.drop_table('product_managers')

    op.drop_index(op.f('ix_workflow_stages_id'), table_name='workflow_stages')
    op.drop_table('workflow_stages')
    op.drop_index(op.f('ix_workflow_events_id'), table_name='workflow_events')
    op.drop_table('workflow_events')

    op.drop_index(op.f('ix_stage_allocations_id'), table_name='stage_allocations')
    op.drop_table('stage_allocations')
    op.drop_index(op.f('ix_workflows_id'), table_name='workflows')
    op.drop_table('workflows')
    op.drop_index(op.f('ix_admins_id'), table_name='admins')
    op.drop_table('admins')

    op.drop_index(op.f('ix_allocations_sub_project_is_active'), table_name='allocations')
    op.create_index(op.f('ix_daily_sheets_encord_project_hash'), 'daily_sheets', ['encord_project_hash'], unique=False)
    op.drop_column('daily_sheets', 'workforce_annotators')
    op.create_foreign_key(None, 'employees', 'employees', ['mentor_id'], ['id'])
    op.drop_column('employees', 'work_description')
    op.drop_column('employees', 'slack_email')
    op.drop_column('employees', 'project_experience')
    op.drop_column('employees', 'work_model')
    op.drop_column('main_projects', 'sentiment')
    op.drop_column('main_projects', 'encord_project_hash')
    op.alter_column('payroll_leave_adjustments', 'unpaid_days',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               existing_nullable=True)
    op.create_foreign_key(None, 'payroll_runs', 'users', ['finalized_by'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'payroll_runs', 'users', ['reopened_by'], ['id'], ondelete='SET NULL')
    op.alter_column('perf_evaluations', 'employee_overall_rating',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('perf_evaluations', 'bonus_suggested',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.drop_column('perf_evaluations', 'strengths')
    op.drop_column('perf_evaluations', 'improvements')
    op.drop_column('perf_evaluations', 'contributions')
    op.alter_column('salary', 'id',
               existing_type=sa.BIGINT(),
               nullable=False,
               autoincrement=True)
    op.create_index(op.f('ix_salary_id'), 'salary', ['id'], unique=False)
    op.drop_constraint(op.f('signup_requests_email_key'), 'signup_requests', type_='unique')
    op.drop_index(op.f('ix_signup_requests_email'), table_name='signup_requests')
    op.create_index(op.f('ix_signup_requests_email'), 'signup_requests', ['email'], unique=True)
    op.create_index(op.f('ix_signup_requests_id'), 'signup_requests', ['id'], unique=False)
    op.alter_column('users', 'employment_type',
               existing_type=sa.TEXT(),
               type_=sa.String(length=50),
               existing_nullable=True)
    op.drop_column('users', 'work_description')
    op.drop_column('users', 'slack_email')
    op.drop_column('users', 'project_experience')
    op.drop_column('users', 'razorpay_email')
    op.alter_column('wfh_requests', 'flagged',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.drop_index(op.f('ix_wfh_date'), table_name='wfh_requests')
    op.drop_index(op.f('ix_wfh_employee_id'), table_name='wfh_requests')
    op.create_index(op.f('ix_wfh_requests_employee_id'), 'wfh_requests', ['employee_id'], unique=False)
    op.create_index(op.f('ix_wfh_requests_id'), 'wfh_requests', ['id'], unique=False)
    op.create_index(op.f('ix_wfh_requests_wfh_date'), 'wfh_requests', ['wfh_date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_wfh_requests_wfh_date'), table_name='wfh_requests')
    op.drop_index(op.f('ix_wfh_requests_id'), table_name='wfh_requests')
    op.drop_index(op.f('ix_wfh_requests_employee_id'), table_name='wfh_requests')
    op.create_index(op.f('ix_wfh_employee_id'), 'wfh_requests', ['employee_id'], unique=False)
    op.create_index(op.f('ix_wfh_date'), 'wfh_requests', ['wfh_date'], unique=False)
    op.alter_column('wfh_requests', 'flagged',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.add_column('users', sa.Column('razorpay_email', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('project_experience', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('slack_email', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('work_description', sa.TEXT(), autoincrement=False, nullable=True))
    op.alter_column('users', 'employment_type',
               existing_type=sa.String(length=50),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.drop_index(op.f('ix_signup_requests_id'), table_name='signup_requests')
    op.drop_index(op.f('ix_signup_requests_email'), table_name='signup_requests')
    op.create_index(op.f('ix_signup_requests_email'), 'signup_requests', ['email'], unique=False)
    op.create_unique_constraint(op.f('signup_requests_email_key'), 'signup_requests', ['email'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_salary_id'), table_name='salary')
    op.alter_column('salary', 'id',
               existing_type=sa.BIGINT(),
               nullable=True,
               autoincrement=True)
    op.add_column('perf_evaluations', sa.Column('contributions', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('perf_evaluations', sa.Column('improvements', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('perf_evaluations', sa.Column('strengths', sa.TEXT(), autoincrement=False, nullable=True))
    op.alter_column('perf_evaluations', 'bonus_suggested',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('perf_evaluations', 'employee_overall_rating',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True)
    op.drop_constraint(None, 'payroll_runs', type_='foreignkey')
    op.drop_constraint(None, 'payroll_runs', type_='foreignkey')
    op.alter_column('payroll_leave_adjustments', 'unpaid_days',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.add_column('main_projects', sa.Column('encord_project_hash', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('main_projects', sa.Column('sentiment', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('employees', sa.Column('work_model', sa.VARCHAR(length=16), server_default=sa.text("'WFO'::character varying"), autoincrement=False, nullable=True))
    op.add_column('employees', sa.Column('project_experience', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('employees', sa.Column('slack_email', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('employees', sa.Column('work_description', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'employees', type_='foreignkey')
    op.add_column('daily_sheets', sa.Column('workforce_annotators', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_daily_sheets_encord_project_hash'), table_name='daily_sheets')
    op.create_index(op.f('ix_allocations_sub_project_is_active'), 'allocations', ['sub_project_id', 'is_active'], unique=False)
    op.create_table('admins',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('name', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('email', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('status', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('employment_type', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('project_experience', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('work_description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('admins_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('admins_pkey')),
    sa.UniqueConstraint('email', name=op.f('admins_email_key'), postgresql_include=[], postgresql_nulls_not_distinct=False),
    sa.UniqueConstraint('user_id', name=op.f('admins_user_id_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_admins_id'), 'admins', ['id'], unique=False)
    op.create_table('workflows',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('owner_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('project_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('status', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('is_template', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('config', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], name=op.f('workflows_owner_id_fkey')),
    sa.ForeignKeyConstraint(['project_id'], ['main_projects.id'], name=op.f('workflows_project_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('workflows_pkey'))
    )
    op.create_index(op.f('ix_workflows_id'), 'workflows', ['id'], unique=False)
    op.create_table('stage_allocations',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('stage_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('resource_type', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('resource_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('resource_label', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('role', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('allocated_hours', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('status', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('assigned_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('assigned_by', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['assigned_by'], ['users.id'], name=op.f('stage_allocations_assigned_by_fkey')),
    sa.ForeignKeyConstraint(['stage_id'], ['workflow_stages.id'], name=op.f('stage_allocations_stage_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('stage_allocations_pkey'))
    )
    op.create_index(op.f('ix_stage_allocations_id'), 'stage_allocations', ['id'], unique=False)
    op.create_table('workflow_events',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('workflow_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('stage_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('actor_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('event_type', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('payload', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], name=op.f('workflow_events_actor_id_fkey')),
    sa.ForeignKeyConstraint(['stage_id'], ['workflow_stages.id'], name=op.f('workflow_events_stage_id_fkey')),
    sa.ForeignKeyConstraint(['workflow_id'], ['workflows.id'], name=op.f('workflow_events_workflow_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('workflow_events_pkey'))
    )
    op.create_index(op.f('ix_workflow_events_id'), 'workflow_events', ['id'], unique=False)
    op.create_table('workflow_stages',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('workflow_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('name', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('stage_order', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('stage_type', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('status', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('entry_criteria', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('exit_criteria', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('sla_hours', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('started_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('completed_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['workflow_id'], ['workflows.id'], name=op.f('workflow_stages_workflow_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('workflow_stages_pkey'))
    )
    op.create_index(op.f('ix_workflow_stages_id'), 'workflow_stages', ['id'], unique=False)
    op.create_table('product_managers',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('name', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('email', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('skills', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('status', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('razorpay_email', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('employment_type', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('project_experience', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('work_description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('product_managers_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('product_managers_pkey')),
    sa.UniqueConstraint('email', name=op.f('product_managers_email_key'), postgresql_include=[], postgresql_nulls_not_distinct=False),
    sa.UniqueConstraint('user_id', name=op.f('product_managers_user_id_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_product_managers_id'), 'product_managers', ['id'], unique=False)
    op.create_table('onboarding_team_members',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('role', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('department', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('email', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('linkedin', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('slack', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('onboarding_team_members_pkey'))
    )
    op.create_index(op.f('ix_onboarding_team_members_id'), 'onboarding_team_members', ['id'], unique=False)
    # ### end Alembic commands ###
