"""add audit_logs table

Hand-written rather than autogenerated on purpose: autogenerate diffs the whole
schema, and this project also builds tables via Base.metadata.create_all() at
startup, so a generated revision tends to include unrelated drops and alters for
pre-existing drift. This revision touches nothing but the new table.

Revision ID: d4e5f6a7b8c9
Revises: c1d2e3f4a5b6
Create Date: 2026-08-04

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd4e5f6a7b8c9'
down_revision: Union[str, Sequence[str], None] = 'c1d2e3f4a5b6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    conn = op.get_bind()
    inspect_obj = sa.inspect(conn)
    if 'audit_logs' in inspect_obj.get_table_names():
        return

    op.create_table(
        'audit_logs',
        sa.Column('id', sa.Integer(), nullable=False),

        # Who acted — snapshotted so the entry still reads correctly after the
        # user is renamed, changes role, or is removed.
        sa.Column('actor_id', sa.Integer(), nullable=True),
        sa.Column('actor_name', sa.String(length=255), nullable=True),
        sa.Column('actor_email', sa.String(length=255), nullable=True),
        sa.Column('actor_role', sa.String(length=30), nullable=True),

        # What happened.
        sa.Column('action', sa.String(length=60), nullable=False),
        sa.Column('action_type', sa.String(length=20), nullable=False),
        sa.Column('category', sa.String(length=30), nullable=False),

        # What it was done to.
        sa.Column('entity_type', sa.String(length=50), nullable=False),
        sa.Column('entity_id', sa.Integer(), nullable=True),
        sa.Column('entity_name', sa.String(length=255), nullable=True),

        # Who it was done to.
        sa.Column('subject_employee_id', sa.Integer(), nullable=True),
        sa.Column('subject_name', sa.String(length=255), nullable=True),

        # The change.
        sa.Column('details', sa.JSON(), nullable=True),
        sa.Column('summary', sa.Text(), nullable=True),

        # Request context.
        sa.Column('ip', sa.String(length=45), nullable=True),
        sa.Column('user_agent', sa.String(length=255), nullable=True),

        sa.Column(
            'created_at',
            sa.TIMESTAMP(),
            server_default=sa.text('now()'),
            nullable=False,
        ),

        sa.PrimaryKeyConstraint('id'),
        # SET NULL rather than CASCADE: removing a user must never silently erase
        # the record of what they did.
        sa.ForeignKeyConstraint(
            ['actor_id'], ['users.id'],
            name='fk_audit_logs_actor_id_users', ondelete='SET NULL',
        ),
        sa.ForeignKeyConstraint(
            ['subject_employee_id'], ['employees.id'],
            name='fk_audit_logs_subject_employee_id_employees', ondelete='SET NULL',
        ),
    )

    op.create_index(op.f('ix_audit_logs_id'), 'audit_logs', ['id'], unique=False)

    # Newest-first default listing. The id tiebreaker keeps pagination stable when
    # several rows share a timestamp.
    op.create_index(
        'ix_audit_logs_created_at_id', 'audit_logs',
        [sa.text('created_at DESC'), sa.text('id DESC')],
    )
    # "What did this person do?"
    op.create_index(
        'ix_audit_logs_actor_created', 'audit_logs',
        ['actor_id', sa.text('created_at DESC')],
    )
    # "What was done to this person?"
    op.create_index(
        'ix_audit_logs_subject_created', 'audit_logs',
        ['subject_employee_id', sa.text('created_at DESC')],
    )
    # Timeline of a single leave / employee.
    op.create_index(
        'ix_audit_logs_entity', 'audit_logs', ['entity_type', 'entity_id'],
    )
    # Backs the category filter pills.
    op.create_index(
        'ix_audit_logs_category_created', 'audit_logs',
        ['category', sa.text('created_at DESC')],
    )


def downgrade() -> None:
    op.drop_index('ix_audit_logs_category_created', table_name='audit_logs')
    op.drop_index('ix_audit_logs_entity', table_name='audit_logs')
    op.drop_index('ix_audit_logs_subject_created', table_name='audit_logs')
    op.drop_index('ix_audit_logs_actor_created', table_name='audit_logs')
    op.drop_index('ix_audit_logs_created_at_id', table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_id'), table_name='audit_logs')
    op.drop_table('audit_logs')
